version: '3.8'

services:

    daily-trends:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        stdin_open: true
        tty: true
        container_name: daily-trends
        volumes:
            - ./:/app
            - auth_node_modules:/app/node_modules
        ports:
            - 8080:8080
            - 9229:9229

volumes:
    auth_node_modules:

networks:
    default:
        name: daily-trends-environment-network
