version: "3.8"

services:
    news-server:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        environment:
            - MONGODB_URL=mongodb://admin:pass@mongo:27017/news?authSource=admin
            - PORT=8080
            - PUBSUB_EMULATOR_HOST=pubsub_emulator:8432
            - PUBSUB_PROJECT_ID=fake_project
        stdin_open: true
        tty: true
        container_name: news-server
        entrypoint: ["npm", "run", "dev:news:server"]
        volumes:
            - ./:/app
            - news-server_node_modules:/app/node_modules
        ports:
            - 8080:8080
        depends_on:
            - mongo

    news-worker:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        environment:
            - MONGODB_URL=mongodb://admin:pass@mongo:27017/news?authSource=admin
            - PORT=8082
            - PUBSUB_EMULATOR_HOST=pubsub_emulator:8432
            - PUBSUB_PROJECT_ID=fake_project
        stdin_open: true
        tty: true
        container_name: news-worker
        entrypoint: ["npm", "run", "dev:news:worker"]
        volumes:
            - ./:/app
            - news-worker_node_modules:/app/node_modules
        ports:
            - 8082:8082
        depends_on:
            - mongo

    content-scraper:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        environment:
            - PORT=8083
            - PUBSUB_EMULATOR_HOST=pubsub_emulator:8432
            - PUBSUB_PROJECT_ID=fake_project
        stdin_open: true
        tty: true
        container_name: content-scraper
        entrypoint: ["npm", "run", "dev:content:scraper"]
        volumes:
            - ./:/app
            - content-scraper_node_modules:/app/node_modules
        ports:
            - 8083:8083

    mongo:
        image: mongo:7.0-jammy
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017

    mongo_express:
        image: mongo-express:1-20-alpine3.18
        container_name: mongo_express
        logging:
            driver: none
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@mongo:27017/daily-trends?authSource=admin
        ports:
            - 8081:8081

    pubsub_emulator:
        image: storytel/gcp-pubsub-emulator
        container_name: pubsub_emulator
        ports:
            - 8432:8432
        command: --host=0.0.0.0 --port=8432

volumes:
    news-server_node_modules:
    news-worker_node_modules:
    content-scraper_node_modules:
